

class SkillMethodID(object):

    BONUS_TREASURE = 0
    BONUS_ARTIFACTS = 1
    BONUS_RELICS = 2
    BONUS_HERB = 3
    BONUS_ORE = 4
    BONUS_GAME = 5
    BONUS_SCRAP = 6

    DETECT_TREASURE = 7
    DETECT_ARTIFACTS = 8
    DETECT_RELICS = 9
    DETECT_HERB = 10
    DETECT_ORE = 11
    DETECT_GAME = 12
    DETECT_SCRAP = 13

